BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE NOT NULL,
  display_name text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'USER',
  scope_id text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(lower(email));
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role) WHERE active = true;

CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference text UNIQUE NOT NULL,
  patient_code text,
  vehicle_id bigint,
  status text NOT NULL DEFAULT 'PENDING',
  service_type text,
  pickup_time timestamptz,
  dropoff_time timestamptz,
  pickup_location text,
  dropoff_location text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bookings_reference ON bookings(reference);
CREATE INDEX IF NOT EXISTS idx_bookings_status_time ON bookings(status, created_at DESC);

INSERT INTO schema_migrations(version,description) VALUES('001.001','Base schema: users and bookings tables') ON CONFLICT(version) DO NOTHING;

COMMIT;
