BEGIN;

CREATE TABLE IF NOT EXISTS sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_digest text UNIQUE NOT NULL,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  ip_address text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_token_digest ON sessions(token_digest);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  action text NOT NULL,
  actor_id bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_role text,
  changes jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log(actor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS trip_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference text NOT NULL REFERENCES bookings(reference) ON DELETE CASCADE,
  status text NOT NULL,
  status_label text,
  note text,
  actor text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trip_status_history_booking ON trip_status_history(booking_reference, created_at DESC);

INSERT INTO schema_migrations(version,description) VALUES('002.001','Sessions, audit logs and trip history tables for authentication and compliance') ON CONFLICT(version) DO NOTHING;

COMMIT;
