import React, {useMemo, useState} from 'react';
import {motion, AnimatePresence} from 'framer-motion';
import {Ambulance, Accessibility, ArrowRight, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileCheck2, Languages, MapPin, Menu, MessageCircle, Phone, Route, ShieldCheck, Stethoscope, Users, Van, X} from 'lucide-react';
import './styles.css';
import {calculateQuote, loadPricing} from './services/pricingService.js';
import {createTrip} from './services/tripStore.js';

const services=[
 {icon:Accessibility,title:'Wheelchair Transportation',tag:'Accessible',copy:'Private, door-through-door transportation with securement support and patient-centered assistance.',accent:'blue'},
 {icon:Van,title:'Stretcher & Bariatric',tag:'Specialized',copy:'Non-emergency stretcher and bariatric-capable transportation coordinated around patient needs.',accent:'teal'},
 {icon:Ambulance,title:'Ambulance Services',tag:'Medical',copy:'Professional scheduled ambulance transportation and inter-facility coordination.',accent:'red'},
 {icon:CalendarDays,title:'Dialysis & Recurring Trips',tag:'Reliable',copy:'Standing-order scheduling designed to support continuity of care and reduce missed appointments.',accent:'purple'},
 {icon:Building2,title:'Hospital Discharge',tag:'Coordinated',copy:'Clear coordination among discharge teams, families, destinations and Nexus operations.',accent:'orange'},
 {icon:Route,title:'Medical Shuttle',tag:'Community',copy:'Accessible group and facility shuttle options for healthcare and senior programs.',accent:'green'}
];
const portalCards=[
 {icon:CalendarDays,title:'Schedule & manage rides',copy:'Submit one-time or recurring requests through one centralized workflow.'},
 {icon:MapPin,title:'Track status and ETA',copy:'See request status, driver assignment and arrival updates.'},
 {icon:FileCheck2,title:'Invoices & reports',copy:'Access ride history, downloadable invoices and service reporting.'},
 {icon:Users,title:'Facility user controls',copy:'Manage schedulers, roles and location-level access.'}
];
const journey=[['01','Request','Select service, pickup, destination, timing and mobility needs.'],['02','Coordinate','Nexus reviews availability, vehicle requirements and care instructions.'],['03','Stay informed','Patient, family and facility receive clear ride-status updates.'],['04','Arrive safely','Door-through-door support and trip completion confirmation.']];

function App(){
 const [mobile,setMobile]=useState(false); const [booking,setBooking]=useState(false); const [partner,setPartner]=useState(false); const [service,setService]=useState('');
 const openBooking=(s='')=>{setService(s);setBooking(true)};
 return <div>
  <header className="topbar"><div className="shell nav">
   <a className="brand" href="#home" aria-label="Nexus Medical Transit home"><img className="nexusLogo" src="./nexus-logo.png" alt="Nexus Medical Transit" /></a>
   <nav className={mobile?'navlinks open':'navlinks'}>{['Services','Patient Experience','Coverage','Facilities','Safety & Quality'].map(x=><a key={x} href={'#'+x.toLowerCase().replaceAll(' ','-').replace('&','and')} onClick={()=>setMobile(false)}>{x}</a>)}</nav>
   <div className="navRight"><a className="call" href="tel:+18887604990"><Phone size={18}/><span><small>Call Nexus</small><b>(888) 760-4990</b></span></a><button className="primary" onClick={()=>openBooking()}>Book a Ride</button><button className="menuBtn" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div>
  </div></header>

  <main id="home">
   <section className="hero"><div className="heroGlow one"/><div className="heroGlow two"/><div className="shell heroGrid">
    <motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.65}} className="heroCopy">
     <div className="eyebrow"><span/> Washington Metropolitan Healthcare Mobility</div>
     <h1>Every medical journey deserves <em>care, clarity and dignity.</em></h1>
     <p>Nexus Medical Transit delivers accessible wheelchair, stretcher, shuttle and ambulance transportation throughout Maryland, Washington, DC and Northern Virginia.</p>
     <div className="heroActions"><button className="primary xl" onClick={()=>openBooking()}>Request Transportation <ArrowRight size={18}/></button><button className="secondary xl" onClick={()=>setPartner(true)}>Facility Solutions</button></div>
     <div className="proof"><span><CheckCircle2/>Door-through-door support</span><span><CheckCircle2/>Multilingual assistance</span><span><CheckCircle2/>Accessible fleet options</span></div>
    </motion.div>
    <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{delay:.15,duration:.7}} className="heroProduct">
      <div className="productTop"><div><small>Nexus Care Coordination</small><strong>Transportation request center</strong></div><span className="available"><i/>Requests open</span></div>
      <div className="routeCanvas"><div className="routeLine a"/><div className="routeLine b"/><span className="pin p1"><Building2/></span><span className="pin p2"><Stethoscope/></span><span className="vehicle"><Ambulance/></span><div className="regionLabel md">MARYLAND</div><div className="regionLabel dc">DC</div><div className="regionLabel va">VIRGINIA</div></div>
      <div className="requestCard"><div><small>Start a transportation request</small><strong>Patient, family or facility</strong></div><button onClick={()=>openBooking()}><ArrowRight/></button></div>
      <div className="miniMetrics"><div><Accessibility/><span><b>Accessible</b><small>Mobility-first service</small></span></div><div><MessageCircle/><span><b>Connected</b><small>Clear ride updates</small></span></div></div>
    </motion.div>
   </div>
   <div className="shell serviceStrip">{[{i:Accessibility,t:'Wheelchair',s:'Private accessible transport'},{i:Van,t:'Stretcher',s:'Non-emergency support'},{i:Ambulance,t:'Ambulance',s:'Medical transport'},{i:Route,t:'Shuttle',s:'Facility mobility'}].map(({i:I,t,s})=><div key={t}><span><I/></span><p><b>{t}</b><small>{s}</small></p></div>)}</div>
   </section>

   <section id="services" className="section"><div className="shell"><Header kicker="Complete mobility support" title="The right level of care for every journey." copy="Clear service pathways for patients, families, discharge planners and healthcare teams."/><div className="services">{services.map(({icon:I,title,tag,copy,accent})=><motion.article whileHover={{y:-7}} key={title} className={'service '+accent}><div className="serviceHead"><span><I/></span><small>{tag}</small></div><h3>{title}</h3><p>{copy}</p><button onClick={()=>openBooking(title)}>Request this service <ChevronRight size={17}/></button></motion.article>)}</div></div></section>

   <section id="patient-experience" className="section muted"><div className="shell split"><div><div className="eyebrow dark"><span/> A better patient journey</div><h2>Confidence before, during and after the ride.</h2><p className="lead">The new Nexus experience combines compassionate care with practical technology—without replacing the human support patients rely on.</p><div className="journey">{journey.map(([n,t,c])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{c}</p></div></article>)}</div></div><div className="phoneMock"><div className="phoneTop"><span/><b>Nexus Trip Status</b><button>•••</button></div><div className="phoneMap"><div className="street one"/><div className="street two"/><div className="street three"/><span className="mapStart"/><span className="mapEnd"/><span className="mapVan"><Ambulance/></span></div><div className="nextUpdate"><div><small>Next update</small><b>Driver assignment pending</b></div><span>Coordinating</span></div><div className="phoneTimeline">{['Request received','Coordination review','Driver assigned','Safe arrival'].map((x,i)=><div className={i===0?'done':i===1?'active':''} key={x}><b>{i===0?'✓':i+1}</b><span><strong>{x}</strong><small>{['Transportation details submitted','Matching service and availability','Vehicle and arrival window shared','Trip completion confirmed'][i]}</small></span></div>)}</div></div></div></section>

   <section id="coverage" className="section darkSection"><div className="shell coverageGrid"><div className="regionalMap"><div className="mapLabel md">MARYLAND</div><div className="mapLabel dc">DC</div><div className="mapLabel va">VIRGINIA</div><svg viewBox="0 0 620 500"><path d="M70 390 C180 330 230 210 335 270 S470 375 560 115"/><path d="M115 170 C235 250 345 205 520 325"/></svg><span className="dot d1"/><span className="dot d2"/><span className="dot d3"/><span className="dot d4"/></div><div><div className="eyebrow"><span/> Regional coverage</div><h2>Local coordination across the capital region.</h2><p className="lead lightText">Transportation throughout Maryland, Washington, DC and Northern Virginia, subject to trip needs and availability.</p><div className="coverageList"><article><b>Maryland</b><span>Montgomery, Prince George’s, Frederick, Howard, Anne Arundel and surrounding communities.</span></article><article><b>Washington, DC</b><span>Hospital discharge, dialysis, rehabilitation and specialty appointments.</span></article><article><b>Northern Virginia</b><span>Arlington, Alexandria, Fairfax and surrounding communities.</span></article></div><button className="lightButton" onClick={()=>openBooking()}>Check a trip location</button></div></div></section>

   <section id="facilities" className="section"><div className="shell split"><div><div className="eyebrow dark"><span/> Facility partnership portal</div><h2>Built for case managers, schedulers and care teams.</h2><p className="lead">We are reusing the Nexus facility workflows already designed: centralized ride requests, recurring scheduling, ETA visibility, billing documents and role-based access.</p><div className="portalGrid">{portalCards.map(({icon:I,title,copy})=><article key={title}><I/><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="heroActions"><button className="primary xl" onClick={()=>setPartner(true)}>Become a Facility Partner</button><a className="outline xl" href="tel:+18887604990">Speak with Nexus</a></div></div><FacilityPreview/></div></section>

   <section id="safety-and-quality" className="section muted"><div className="shell qualityGrid"><div><div className="eyebrow dark"><span/> Safety, quality and compliance</div><h2>Operational accountability made visible.</h2><p className="lead">The platform will bring together the QA transparency work, complaint process, mechanical-failure reporting, policies, employee acknowledgments and compliance documentation already created for Nexus.</p></div><div className="qualityCards"><article><ShieldCheck/><div><h3>Quality & complaint center</h3><p>Clear public and internal pathways for feedback, review and continuous improvement.</p></div></article><article><FileCheck2/><div><h3>Compliance document library</h3><p>Centralized policies, acknowledgments, training records and audit-ready documentation.</p></div></article><article><Van/><div><h3>Mechanical failure workflow</h3><p>Driver reporting, vehicle status, fleet notifications and corrective action tracking.</p></div></article></div></div></section>

   <section className="cta"><div className="shell ctaInner"><div><div className="eyebrow"><span/> Access Drives Equity</div><h2>Let’s coordinate the next medical journey.</h2><p>Request a ride online or speak directly with the Nexus team.</p></div><div className="heroActions"><button className="white xl" onClick={()=>openBooking()}>Request Transportation</button><a className="ghost xl" href="tel:+18887604990">Call (888) 760-4990</a></div></div></section>
  </main>

  <footer><div className="shell footerGrid"><div className="footerBrand"><a className="brand footerLogoLink" href="#home" aria-label="Nexus Medical Transit home"><img className="nexusLogo footerNexusLogo" src="./nexus-footer-logo.png" alt="Nexus Medical Transit" /></a><p>Compassionate, timely and inclusive healthcare mobility across the Washington Metropolitan Area.</p></div><div><h4>Patients & Families</h4><button onClick={()=>openBooking()}>Book Transportation</button><a href="#services">Services</a><a href="#safety-and-quality">Safety & Quality</a></div><div><h4>Healthcare Partners</h4><button onClick={()=>setPartner(true)}>Facility Partnership</button><a href="#coverage">Coverage</a><a href="#facilities">Facility Portal</a></div><div><h4>Contact</h4><a href="tel:+18887604990">(888) 760-4990</a><a href="mailto:contact@nexusmt.com">contact@nexusmt.com</a><a href="https://nexusmt.com">nexusmt.com</a></div></div><div className="shell footerBottom"><span>© 2026 Nexus Medical Transit LLC</span><span>For emergencies, call 911.</span></div></footer>

  <AnimatePresence>{booking&&<Modal title="Request Transportation" subtitle="This React prototype creates a local request summary only. It does not transmit patient information." close={()=>setBooking(false)}><BookingForm initial={service}/></Modal>}{partner&&<Modal title="Facility Partnership" subtitle="Tell Nexus about your organization and transportation coordination needs." close={()=>setPartner(false)}><PartnerForm/></Modal>}</AnimatePresence>
 </div>
}

function Header({kicker,title,copy}){return <div className="sectionHeader"><div><div className="eyebrow dark"><span/> {kicker}</div><h2>{title}</h2></div><p>{copy}</p></div>}
function FacilityPreview(){return <div className="facilityPreview"><div className="previewTop"><div><small>Facility workspace</small><strong>Ride management</strong></div><span><i/>Portal preview</span></div><div className="previewStats"><article><small>Scheduling</small><b>One-time & recurring</b></article><article><small>Visibility</small><b>Status & ETA</b></article><article><small>Documents</small><b>Invoices & reports</b></article></div><div className="previewTable"><div className="previewRow head"><span>Journey</span><span>Service</span><span>Status</span></div><div className="previewRow"><span>Hospital → Residence</span><span>Wheelchair</span><b className="amber">Reviewing</b></div><div className="previewRow"><span>Recurring Dialysis</span><span>Ambulatory</span><b className="green">Confirmed</b></div><div className="previewRow"><span>Inter-facility</span><span>Stretcher</span><b className="blue">Coordinating</b></div></div></div>}
function Modal({title,subtitle,close,children}){return <motion.div className="modalBackdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><motion.div className="modal" initial={{y:25,opacity:0,scale:.98}} animate={{y:0,opacity:1,scale:1}} exit={{y:15,opacity:0}}><button className="close" onClick={close}><X/></button><div className="eyebrow dark"><span/> Nexus Care Coordination</div><h2>{title}</h2><p>{subtitle}</p>{children}</motion.div></motion.div>}
function BookingForm({initial}){
 const [done,setDone]=useState(false);
 const [form,setForm]=useState({name:'',phone:'',email:'',service:initial||'',pickup:'',destination:'',date:'',time:'',miles:10,waitMinutes:0,roundTrip:false,notes:''});
 const ref=useMemo(()=>`NMT-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.floor(1000+Math.random()*9000)}`,[]);
 const dateObj=form.date?new Date(`${form.date}T${form.time||'12:00'}`):null;
 const afterHours=!!dateObj&&(dateObj.getHours()<7||dateObj.getHours()>=19);
 const weekend=!!dateObj&&[0,6].includes(dateObj.getDay());
 const quote=useMemo(()=>calculateQuote({service:form.service,miles:form.miles,waitMinutes:form.waitMinutes,roundTrip:form.roundTrip,afterHours,weekend,pricing:loadPricing()}),[form.service,form.miles,form.waitMinutes,form.roundTrip,afterHours,weekend]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const submit=e=>{e.preventDefault();createTrip({...form,reference:ref,quote,payer:'Self-pay'});setDone(true)};
 return done?<div className="success"><CheckCircle2/><h3>Transportation request created</h3><p>Reference: <b>{ref}</b></p><div className="quoteSummary"><span>Estimated fare</span><strong>${quote.total.toFixed(2)}</strong><small>The request is now available to Dispatch and Billing in this browser.</small></div><div className="successActions"><a className="primary xl" href="/dispatch.html">Open Dispatch</a><a className="outline xl" href="/billing.html">Open Billing</a></div></div>:<form className="form" onSubmit={submit}>
  <label>Name<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Phone<input required type="tel" value={form.phone} onChange={e=>set('phone',e.target.value)}/></label>
  <label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Service<select required value={form.service} onChange={e=>set('service',e.target.value)}><option value="">Choose a service</option>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Ambulatory Transportation</option><option>Broda Chair Transportation</option><option>BLS Ambulance</option><option>ALS I Ambulance</option><option>ALS II Ambulance</option></select></label>
  <label className="wide">Pickup<input required value={form.pickup} onChange={e=>set('pickup',e.target.value)}/></label><label className="wide">Destination<input required value={form.destination} onChange={e=>set('destination',e.target.value)}/></label>
  <label>Date<input required type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label><label>Time<input required type="time" value={form.time} onChange={e=>set('time',e.target.value)}/></label>
  <label>Estimated miles<input min="0" step="0.1" required type="number" value={form.miles} onChange={e=>set('miles',e.target.value)}/></label><label>Wait time (minutes)<input min="0" step="15" type="number" value={form.waitMinutes} onChange={e=>set('waitMinutes',e.target.value)}/></label>
  <label className="check wide"><input type="checkbox" checked={form.roundTrip} onChange={e=>set('roundTrip',e.target.checked)}/>Round trip</label>
  <label className="wide">Mobility or coordination notes<textarea rows="3" value={form.notes} onChange={e=>set('notes',e.target.value)}/></label>
  <section className="fareCard wide" aria-live="polite"><div><small>NIPE estimated fare</small><strong>${quote.total.toFixed(2)}</strong></div><dl><div><dt>Base</dt><dd>${quote.breakdown.base.toFixed(2)}</dd></div><div><dt>Mileage</dt><dd>${quote.breakdown.mileage.toFixed(2)}</dd></div><div><dt>Wait</dt><dd>${quote.breakdown.wait.toFixed(2)}</dd></div>{afterHours&&<div><dt>After-hours</dt><dd>${quote.breakdown.afterHours.toFixed(2)}</dd></div>}{weekend&&<div><dt>Weekend</dt><dd>${quote.breakdown.weekend.toFixed(2)}</dd></div>}</dl><p>Estimate only; final fare is subject to route validation, service confirmation and contract terms.</p></section>
  <label className="check wide"><input required type="checkbox"/>This is not an emergency request and service is subject to confirmation.</label><button className="primary xl wide">Confirm Request & Create Trip</button>
 </form>
}
function PartnerForm(){const [done,setDone]=useState(false);return done?<div className="success"><CheckCircle2/><h3>Partnership summary created</h3><p>Nexus can now connect this workflow to email, CRM or the facility portal backend.</p></div>:<form className="form" onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Organization<input required/></label><label>Type<select required defaultValue=""><option value="">Choose</option><option>Hospital</option><option>Dialysis Center</option><option>Skilled Nursing</option><option>Assisted Living</option><option>Rehabilitation</option><option>Other</option></select></label><label>Contact name<input required/></label><label>Work email<input required type="email"/></label><label className="wide">Transportation needs<textarea required rows="4"/></label><button className="primary xl wide">Create Partnership Summary</button></form>}

export default App;
